blacklist: []
build_space: build
catkin_make_args: []
cmake_args: []
devel_layout: linked
devel_space: devel
extend_path: /home/djole/Master/LWR/software/isir/lwr_ws/install
install: false
install_space: install
isolate_install: false
jobs_args:
- -j8
log_space: logs
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
